dry_run: true
logging:
  level: INFO
  enabled: true
  dir: ~/.local/share/awsbreaker/logs
aws:
  profile: default
  aws_access_key_id: "" # leave empty if using credentials file
  aws_secret_access_key: ""
  aws_session_token: "" # optional
  credential_file_path: ~/.aws/credentials
  max_workers: 4
  region:
    # - all # to scan through all region (WIP)
    - us-east-1
    - ap-south-1
  services:
    # - all to scan for all services (WIP)
    - ec2
    - lambda
